In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("US_honey_dataset_updated.csv")

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1115 non-null   int64
 1   state                1115 non-null   str
 2   colonies_number      1115 non-null   int64
 3   yield_per_colony     1115 non-null   int64
 4   production           1115 non-null   int64
 5   stocks               1115 non-null   int64
 6   average_price        1115 non-null   float64
 7   value_of_production  1115 non-null   int64
 8   year                 1115 non-null   int64
dtypes: float64(1), int64(7), str(1)
memory usage: 78.5 KB

In [4]:
df.describe()

,Unnamed: 0,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
count,1115.00000,1115.000000,1115.000000,1.115000e+03,1.115000e+03,1115.000000,1.115000e+03,1115.000000
mean,557.00000,62438.565022,59.743498,2.851268e+06,1.172625e+06,140.623076,5.667412e+06,2007.740807
std,322.01708,92648.175955,19.940500,5.561202e+06,2.049556e+06,107.011544,9.459460e+06,7.823002
min,0.00000,2000.000000,19.000000,1.200000e+04,9.000000e+03,1.300000,1.060000e+05,1995.000000
25%,278.50000,9000.000000,45.000000,2.460000e+05,1.125000e+05,70.000000,1.008000e+06,2001.000000
50%,557.00000,26000.000000,57.000000,8.280000e+05,3.700000e+05,128.000000,2.281000e+06,2008.000000
75%,835.50000,69000.000000,71.000000,2.700000e+06,1.253500e+06,193.000000,5.704000e+06,2015.000000
max,1114.00000,550000.000000,155.000000,3.906000e+07,1.354500e+07,874.000000,8.385900e+07,2021.000000

In [5]:
df['state'].unique()

<StringArray>
[      'Alabama',       'Arizona',      'Arkansas',    'California',
      'Colorado',       'Florida',       'Georgia',        'Hawaii',
         'Idaho',      'Illinois',       'Indiana',          'Iowa',
        'Kansas',      'Kentucky',     'Louisiana',         'Maine',
      'Maryland',      'Michigan',     'Minnesota',   'Mississippi',
      'Missouri',       'Montana',      'Nebraska',        'Nevada',
     'NewJersey',     'NewMexico',       'NewYork', 'NorthCarolina',
   'NorthDakota',          'Ohio',      'Oklahoma',        'Oregon',
  'Pennsylvania', 'SouthCarolina',   'SouthDakota',     'Tennessee',
         'Texas',          'Utah',       'Vermont',      'Virginia',
    'Washington',  'WestVirginia',     'Wisconsin',       'Wyoming']
Length: 44, dtype: str

In [6]:
for i in df['state'].unique():
    print(i)

Alabama
Arizona
Arkansas
California
Colorado
Florida
Georgia
Hawaii
Idaho
Illinois
Indiana
Iowa
Kansas
Kentucky
Louisiana
Maine
Maryland
Michigan
Minnesota
Mississippi
Missouri
Montana
Nebraska
Nevada
NewJersey
NewMexico
NewYork
NorthCarolina
NorthDakota
Ohio
Oklahoma
Oregon
Pennsylvania
SouthCarolina
SouthDakota
Tennessee
Texas
Utah
Vermont
Virginia
Washington
WestVirginia
Wisconsin
Wyoming

In [7]:
df.groupby('state')['production'].sum()

state
Alabama           14467000
Arizona           38844000
Arkansas          51846000
California       423876000
Colorado          32660000
Florida          280934000
Georgia           57426000
Hawaii            15420000
Idaho             87188000
Illinois           9864000
Indiana            9686000
Iowa              48607000
Kansas            14138000
Kentucky           3224000
Louisiana         60568000
Maine              4762000
Maryland           1975000
Michigan         101063000
Minnesota        176581000
Mississippi       21235000
Missouri          17904000
Montana          197173000
Nebraska          63655000
Nevada             7399000
NewJersey          6913000
NewMexico         10082000
NewYork           78444000
NorthCarolina      8909000
NorthDakota      513742000
Ohio              22485000
Oklahoma           2055000
Oregon            43789000
Pennsylvania      21370000
SouthCarolina      2823000
SouthDakota      355726000
Tennessee          6857000
Texas            129441000
Utah              20369000
Vermont            7032000
Virginia           5153000
Washington        53238000
WestVirginia       6411000
Wisconsin         99909000
Wyoming           43921000
Name: production, dtype: int64

In [8]:
df['state'].value_counts()

state
Alabama          27
Arizona          27
Arkansas         27
California       27
Colorado         27
Florida          27
Georgia          27
Hawaii           27
Idaho            27
Illinois         27
Indiana          27
Iowa             27
Kansas           27
Louisiana        27
Maine            27
Michigan         27
Minnesota        27
Mississippi      27
Missouri         27
Montana          27
Nebraska         27
NewJersey        27
NewYork          27
NorthCarolina    27
NorthDakota      27
Ohio             27
Oregon           27
Pennsylvania     27
SouthDakota      27
Tennessee        27
Texas            27
Utah             27
Vermont          27
Virginia         27
Washington       27
WestVirginia     27
Wisconsin        27
Wyoming          27
Kentucky         26
NewMexico        18
Nevada           15
SouthCarolina    12
Maryland          9
Oklahoma          9
Name: count, dtype: int64

In [9]:
df.groupby('state')['state'].count()

state
Alabama          27
Arizona          27
Arkansas         27
California       27
Colorado         27
Florida          27
Georgia          27
Hawaii           27
Idaho            27
Illinois         27
Indiana          27
Iowa             27
Kansas           27
Kentucky         26
Louisiana        27
Maine            27
Maryland          9
Michigan         27
Minnesota        27
Mississippi      27
Missouri         27
Montana          27
Nebraska         27
Nevada           15
NewJersey        27
NewMexico        18
NewYork          27
NorthCarolina    27
NorthDakota      27
Ohio             27
Oklahoma          9
Oregon           27
Pennsylvania     27
SouthCarolina    12
SouthDakota      27
Tennessee        27
Texas            27
Utah             27
Vermont          27
Virginia         27
Washington       27
WestVirginia     27
Wisconsin        27
Wyoming          27
Name: state, dtype: int64

In [15]:
def check():
    group = input("Enter column of the group")
    column = input("Enter the column of agreegation")
    choice = int(input("Enter choice 1. count, 2. sum , 3. mode"))
    if choice == 1:
        print(df.groupby(group)[column].count())
    elif choice ==2:
        print(df.groupby(group)[column].sum())
    elif choice == 3:
        print(df.groupby(group)[column].agg(lambda x : x.mode()[0]))
    else:
        print("Invalid choice")
check()

Enter column of the group state
Enter the column of agreegation production
Enter choice 1. count, 2. sum , 3. mode 3

state
Alabama             13000
Arizona           1920000
Arkansas           176000
California       30000000
Colorado          2700000
Florida            529000
Georgia           3135000
Hawaii              18000
Idaho             4600000
Illinois           814000
Indiana             82000
Iowa               463000
Kansas              39000
Kentucky           150000
Louisiana          141000
Maine               17000
Maryland           276000
Michigan          3960000
Minnesota          285000
Mississippi       1372000
Missouri            92000
Montana           1934000
Nebraska           223000
Nevada             854000
NewJersey          324000
NewMexico           99000
NewYork            665000
NorthCarolina      495000
NorthDakota       2266000
Ohio              1296000
Oklahoma           141000
Oregon             456000
Pennsylvania       177000
SouthCarolina      810000
SouthDakota      21375000
Tennessee          385000
Texas              384000
Utah                92000
Vermont             43000
Virginia           266000
Washington        2808000
WestVirginia        32000
Wisconsin          683000
Wyoming            146000
Name: production, dtype: int64

In [16]:
df.groupby('state')['production'].agg(['sum','mean','max'])

                     sum          mean       max
state
Alabama         14467000  5.358148e+05   1248000
Arizona         38844000  1.438667e+06   4108000
Arkansas        51846000  1.920222e+06   5655000
California     423876000  1.569911e+07  39060000
Colorado        32660000  1.209630e+06   2700000
Florida        280934000  1.040496e+07  25200000
Georgia         57426000  2.126889e+06   5100000
Hawaii          15420000  5.711111e+05   1314000
Idaho           87188000  3.229185e+06   7680000
Illinois         9864000  3.653333e+05    814000
Indiana          9686000  3.587407e+05    828000
Iowa            48607000  1.800259e+06   3900000
Kansas          14138000  5.236296e+05   1207000
Kentucky         3224000  1.240000e+05    280000
Louisiana       60568000  2.243259e+06   5472000
Maine            4762000  1.763704e+05    495000
Maryland         1975000  2.194444e+05    308000
Michigan       101063000  3.743074e+06   8924000
Minnesota      176581000  6.540037e+06  13530000
Mississippi     21235000  7.864815e+05   1575000
Missouri        17904000  6.631111e+05   1848000
Montana        197173000  7.302704e+06  14030000
Nebraska        63655000  2.357593e+06   4875000
Nevada           7399000  4.932667e+05    854000
NewJersey        6913000  2.560370e+05    539000
NewMexico       10082000  5.601111e+05   1235000
NewYork         78444000  2.905333e+06   5880000
NorthCarolina    8909000  3.299630e+05    714000
NorthDakota    513742000  1.902748e+07  35100000
Ohio            22485000  8.327778e+05   1760000
Oklahoma         2055000  2.283333e+05    380000
Oregon          43789000  1.621815e+06   3245000
Pennsylvania    21370000  7.914815e+05   1620000
SouthCarolina    2823000  2.352500e+05    810000
SouthDakota    355726000  1.317504e+07  28435000
Tennessee        6857000  2.539630e+05    549000
Texas          129441000  4.794111e+06   9964000
Utah            20369000  7.544074e+05   1740000
Vermont          7032000  2.604444e+05    623000
Virginia         5153000  1.908519e+05    468000
Washington      53238000  1.971778e+06   3540000
WestVirginia     6411000  2.374444e+05    590000
Wisconsin       99909000  3.700333e+06   8099000
Wyoming         43921000  1.626704e+06   3627000

In [17]:
# to convert expo value to 2 decimal values
pd.set_option('display.float_format','{:.2f}'.format)

In [18]:
# to convert it info full integer
pd.set_option('display.float_format','{:.0f}'.format)

In [19]:
df.groupby('state')['production'].agg(['sum','mean','max'])

                     sum     mean       max
state
Alabama         14467000   535815   1248000
Arizona         38844000  1438667   4108000
Arkansas        51846000  1920222   5655000
California     423876000 15699111  39060000
Colorado        32660000  1209630   2700000
Florida        280934000 10404963  25200000
Georgia         57426000  2126889   5100000
Hawaii          15420000   571111   1314000
Idaho           87188000  3229185   7680000
Illinois         9864000   365333    814000
Indiana          9686000   358741    828000
Iowa            48607000  1800259   3900000
Kansas          14138000   523630   1207000
Kentucky         3224000   124000    280000
Louisiana       60568000  2243259   5472000
Maine            4762000   176370    495000
Maryland         1975000   219444    308000
Michigan       101063000  3743074   8924000
Minnesota      176581000  6540037  13530000
Mississippi     21235000   786481   1575000
Missouri        17904000   663111   1848000
Montana        197173000  7302704  14030000
Nebraska        63655000  2357593   4875000
Nevada           7399000   493267    854000
NewJersey        6913000   256037    539000
NewMexico       10082000   560111   1235000
NewYork         78444000  2905333   5880000
NorthCarolina    8909000   329963    714000
NorthDakota    513742000 19027481  35100000
Ohio            22485000   832778   1760000
Oklahoma         2055000   228333    380000
Oregon          43789000  1621815   3245000
Pennsylvania    21370000   791481   1620000
SouthCarolina    2823000   235250    810000
SouthDakota    355726000 13175037  28435000
Tennessee        6857000   253963    549000
Texas          129441000  4794111   9964000
Utah            20369000   754407   1740000
Vermont          7032000   260444    623000
Virginia         5153000   190852    468000
Washington      53238000  1971778   3540000
WestVirginia     6411000   237444    590000
Wisconsin       99909000  3700333   8099000
Wyoming         43921000  1626704   3627000

In [20]:
# aggregation of different columns
df.groupby('state').agg({
    'production':'sum',
    'average_price':'mean',
    'value_of_production':'mean'})

               production  average_price  value_of_production
state
Alabama          14467000            150              1061778
Arizona          38844000            110              2213778
Arkansas         51846000            106              2732630
California      423876000            109             24221556
Colorado         32660000            119              2364593
Florida         280934000            110             18876667
Georgia          57426000            121              5405370
Hawaii           15420000            138              1847704
Idaho            87188000            106              5168000
Illinois          9864000            216              1362296
Indiana           9686000            155               913259
Iowa             48607000            124              3243074
Kansas           14138000            147              1035926
Kentucky          3224000            202               593346
Louisiana        60568000            103              4800037
Maine             4762000            174               734889
Maryland          1975000            146               303889
Michigan        101063000            123              8068185
Minnesota       176581000            107             11498593
Mississippi      21235000            103              2195000
Missouri         17904000            146              1198963
Montana         197173000            110             15057889
Nebraska         63655000            111              3962889
Nevada            7399000            205               968000
NewJersey         6913000            195              1044481
NewMexico        10082000            122               613833
NewYork          78444000            136              6589667
NorthCarolina     8909000            205              1431296
NorthDakota     513742000            106             43934037
Ohio             22485000            164              2208778
Oklahoma          2055000            134               290889
Oregon           43789000            119              3781815
Pennsylvania     21370000            153              2042704
SouthCarolina     2823000            176              2184833
SouthDakota     355726000            107             22929444
Tennessee         6857000            197              1010222
Texas           129441000            110             10545185
Utah             20369000            111              1487296
Vermont           7032000            174               706815
Virginia          5153000            238               775000
Washington       53238000            119              4437889
WestVirginia      6411000            191               692037
Wisconsin        99909000            126              6534889
Wyoming          43921000            108              3240815

In [24]:
report = df.groupby('state').agg(
    total_production=('production','sum'),
average_production=('production','mean'),
max_production=('production','max')
)

In [25]:
report

               total_production  average_production  max_production
state
Alabama                14467000              535815         1248000
Arizona                38844000             1438667         4108000
Arkansas               51846000             1920222         5655000
California            423876000            15699111        39060000
Colorado               32660000             1209630         2700000
Florida               280934000            10404963        25200000
Georgia                57426000             2126889         5100000
Hawaii                 15420000              571111         1314000
Idaho                  87188000             3229185         7680000
Illinois                9864000              365333          814000
Indiana                 9686000              358741          828000
Iowa                   48607000             1800259         3900000
Kansas                 14138000              523630         1207000
Kentucky                3224000              124000          280000
Louisiana              60568000             2243259         5472000
Maine                   4762000              176370          495000
Maryland                1975000              219444          308000
Michigan              101063000             3743074         8924000
Minnesota             176581000             6540037        13530000
Mississippi            21235000              786481         1575000
Missouri               17904000              663111         1848000
Montana               197173000             7302704        14030000
Nebraska               63655000             2357593         4875000
Nevada                  7399000              493267          854000
NewJersey               6913000              256037          539000
NewMexico              10082000              560111         1235000
NewYork                78444000             2905333         5880000
NorthCarolina           8909000              329963          714000
NorthDakota           513742000            19027481        35100000
Ohio                   22485000              832778         1760000
Oklahoma                2055000              228333          380000
Oregon                 43789000             1621815         3245000
Pennsylvania           21370000              791481         1620000
SouthCarolina           2823000              235250          810000
SouthDakota           355726000            13175037        28435000
Tennessee               6857000              253963          549000
Texas                 129441000             4794111         9964000
Utah                   20369000              754407         1740000
Vermont                 7032000              260444          623000
Virginia                5153000              190852          468000
Washington             53238000             1971778         3540000
WestVirginia            6411000              237444          590000
Wisconsin              99909000             3700333         8099000
Wyoming                43921000             1626704         3627000

In [26]:
df.groupby('state').agg({
    'production':['sum','mean','max'],
    'average_price':['sum','mean','max']
})

              production                    average_price
                     sum     mean       max           sum mean max
state
Alabama         14467000   535815   1248000          4058  150 383
Arizona         38844000  1438667   4108000          2979  110 203
Arkansas        51846000  1920222   5655000          2870  106 206
California     423876000 15699111  39060000          2954  109 216
Colorado        32660000  1209630   2700000          3201  119 226
Florida        280934000 10404963  25200000          2968  110 243
Georgia         57426000  2126889   5100000          3261  121 300
Hawaii          15420000   571111   1314000          3719  138 415
Idaho           87188000  3229185   7680000          2870  106 203
Illinois         9864000   365333    814000          5842  216 542
Indiana          9686000   358741    828000          4183  155 361
Iowa            48607000  1800259   3900000          3342  124 245
Kansas          14138000   523630   1207000          3977  147 403
Kentucky         3224000   124000    280000          5250  202 413
Louisiana       60568000  2243259   5472000          2783  103 218
Maine            4762000   176370    495000          4692  174 543
Maryland         1975000   219444    308000          1310  146 191
Michigan       101063000  3743074   8924000          3312  123 249
Minnesota      176581000  6540037  13530000          2888  107 206
Mississippi     21235000   786481   1575000          2777  103 240
Missouri        17904000   663111   1848000          3942  146 370
Montana        197173000  7302704  14030000          2961  110 221
Nebraska        63655000  2357593   4875000          3004  111 207
Nevada           7399000   493267    854000          3068  205 360
NewJersey        6913000   256037    539000          5263  195 874
NewMexico       10082000   560111   1235000          2197  122 339
NewYork         78444000  2905333   5880000          3664  136 319
NorthCarolina    8909000   329963    714000          5540  205 478
NorthDakota    513742000 19027481  35100000          2863  106 204
Ohio            22485000   832778   1760000          4417  164 393
Oklahoma         2055000   228333    380000          1203  134 183
Oregon          43789000  1621815   3245000          3221  119 243
Pennsylvania    21370000   791481   1620000          4131  153 362
SouthCarolina    2823000   235250    810000          2112  176 457
SouthDakota    355726000 13175037  28435000          2892  107 208
Tennessee        6857000   253963    549000          5318  197 488
Texas          129441000  4794111   9964000          2966  110 224
Utah            20369000   754407   1740000          3003  111 213
Vermont          7032000   260444    623000          4689  174 489
Virginia         5153000   190852    468000          6420  238 585
Washington      53238000  1971778   3540000          3208  119 261
WestVirginia     6411000   237444    590000          5162  191 444
Wisconsin       99909000  3700333   8099000          3411  126 282
Wyoming         43921000  1626704   3627000          2904  108 211

In [28]:
df.groupby('state')['production'].sum().nlargest(5)

state
NorthDakota    513742000
California     423876000
SouthDakota    355726000
Florida        280934000
Montana        197173000
Name: production, dtype: int64

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1115 entries, 0 to 1114
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1115 non-null   int64
 1   state                1115 non-null   str
 2   colonies_number      1115 non-null   int64
 3   yield_per_colony     1115 non-null   int64
 4   production           1115 non-null   int64
 5   stocks               1115 non-null   int64
 6   average_price        1115 non-null   float64
 7   value_of_production  1115 non-null   int64
 8   year                 1115 non-null   int64
dtypes: float64(1), int64(7), str(1)
memory usage: 78.5 KB

In [32]:
df.groupby(['state','year'])['production'].sum()

state    year
Alabama  1995     928000
         1996    1024000
         1997     924000
         1998    1136000
         1999    1156000
                  ...
Wyoming  2017     186000
         2018     175000
         2019     306000
         2020     608000
         2021     242000
Name: production, Length: 1115, dtype: int64

In [37]:
df[(df['state']=='Alabama') & (df['year']==1999)]

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
174,174,Alabama,17000,68,1156000,185000,56,647000,1999

In [38]:
df[(df['state']=='Alabama') & (df['year']==1999)]['production']

174    1156000
Name: production, dtype: int64

In [39]:
df[(df['state']=='Alabama')]

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
0,0,Alabama,16000,58,928000,28000,62,575000,1995
44,44,Alabama,16000,64,1024000,102000,86,881000,1996
88,88,Alabama,14000,66,924000,92000,81,748000,1997
131,131,Alabama,16000,71,1136000,159000,72,818000,1998
174,174,Alabama,17000,68,1156000,185000,56,647000,1999
217,217,Alabama,16000,78,1248000,187000,59,736000,2000
260,260,Alabama,14000,73,1022000,235000,71,726000,2001
303,303,Alabama,12000,86,1032000,103000,111,1146000,2002
347,347,Alabama,13000,82,1066000,43000,126,1343000,2003
391,391,Alabama,12000,87,1044000,282000,140,1462000,2004
431,431,Alabama,13000,66,858000,266000,128,1098000,2005
472,472,Alabama,11000,72,792000,230000,146,1156000,2006
513,513,Alabama,11000,56,616000,209000,141,869000,2007
554,554,Alabama,9000,66,594000,214000,186,1105000,2008
595,595,Alabama,9000,49,441000,66000,182,803000,2009
636,636,Alabama,9000,54,73000,73000,240,1166000,2010
676,676,Alabama,9000,50,63000,63000,251,1130000,2011
716,716,Alabama,8000,54,65000,65000,247,1067000,2012
756,756,Alabama,7000,52,55000,55000,285,1037000,2013
795,795,Alabama,7000,53,26000,26000,353,1310000,2014
835,835,Alabama,7000,47,13000,13000,383,1260000,2015
875,875,Alabama,7000,52,33000,33000,345,1256000,2016
915,915,Alabama,7000,45,22000,22000,288,907000,2017
955,955,Alabama,6000,45,14000,14000,4,1004000,2018
995,995,Alabama,7000,42,44000,44000,3,994000,2019
1035,1035,Alabama,7000,39,66000,66000,6,1507000,2020
1075,1075,Alabama,8000,40,112000,112000,6,1917000,2021

In [40]:
df[(df['state'] == 'Alabama') & (df['year'].isin([2000,2001,2002]))]

,Unnamed: 0,state,colonies_number,yield_per_colony,production,stocks,average_price,value_of_production,year
217,217,Alabama,16000,78,1248000,187000,59,736000,2000
260,260,Alabama,14000,73,1022000,235000,71,726000,2001
303,303,Alabama,12000,86,1032000,103000,111,1146000,2002

In [42]:
df[(df['state'] == 'Alabama') & (df['year'].isin([2000,2001,2002]))]['production']

217    1248000
260    1022000
303    1032000
Name: production, dtype: int64

In [45]:
df[(df['state'] == 'Alabama') & (df['year'].between(2001,2005))]['production']

260    1022000
303    1032000
347    1066000
391    1044000
431     858000
Name: production, dtype: int64