In [1]:
import pandas as pd

In [23]:
df1=pd.DataFrame({
    'name':['rahul','amar'],
    'age':[22,23]
})
df2=pd.DataFrame({
    'name':['neha','priya','hi'],
     'age':[21,22,22]
})

In [26]:
df3=pd.concat([df1,df2],axis = 0).reset_index(drop=True)

In [27]:
df3

    name  age
0  rahul   22
1   amar   23
2   neha   21
3  priya   22
4     hi   22

In [17]:
students = pd.DataFrame({
    'roll':[101,102,103,107,108],
    'name':['amit','sumit','pawan','ram','rajat']
})
marks=pd.DataFrame({
    'roll':[101,102,103,105,106,107,108,109],
    'marks':[45,65,78,45,32,98,56,68]
})

In [19]:
pd.merge(students,marks,on="roll")

   roll   name  marks
0   101   amit     45
1   102  sumit     65
2   103  pawan     78
3   107    ram     98
4   108  rajat     56

In [21]:
pd.merge(students,marks,on="roll",how='right')

   roll   name  marks
0   101   amit     45
1   102  sumit     65
2   103  pawan     78
3   105    NaN     45
4   106    NaN     32
5   107    ram     98
6   108  rajat     56
7   109    NaN     68

In [22]:
pd.merge(students,marks,on="roll",how='outer')

   roll   name  marks
0   101   amit     45
1   102  sumit     65
2   103  pawan     78
3   105    NaN     45
4   106    NaN     32
5   107    ram     98
6   108  rajat     56
7   109    NaN     68