In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Superstore.csv",encoding = 'latin1')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [4]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [5]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [6]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df['Ship Mode'].nunique()

4

In [8]:
ShipCat=[]
for i in df['Ship Mode'].unique():
    ShipCat.append(i)

In [9]:
ShipCat

['Second Class', 'Standard Class', 'First Class', 'Same Day']

In [10]:
df['Customer Name'].nunique()

793

In [11]:
df['Customer ID'].nunique()

793

In [12]:
df['Customer ID'].value_counts().nlargest(780)

Customer ID
WB-21850    37
JL-15835    34
PP-18955    34
MA-17560    34
SV-20365    32
            ..
TT-21265     3
MW-18235     3
RH-19555     3
BO-11425     2
EL-13735     2
Name: count, Length: 780, dtype: int64

In [13]:
def val_counts(CustomerId_Count):
    if CustomerId_Count> 30:
        return "Great"
    elif CustomerId_Count > 15:
        return "Average"
    elif CustomerId_Count > 5:
        return 'Below'
    else:
        return 'New Customer'

In [14]:
customer_freq = df['Customer ID'].value_counts()
df['Cust_Category']=df['Customer ID'].map(customer_freq).apply(val_counts)

In [15]:
df['Cust_Category']

0       New Customer
1       New Customer
2              Below
3              Below
4              Below
            ...
9989         Average
9990           Below
9991           Below
9992           Below
9993         Average
Name: Cust_Category, Length: 9994, dtype: object

In [16]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cust_Category
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,New Customer
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,New Customer
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,Below
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Below
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Below

In [17]:
Cust_Category_freq=df.groupby('Cust_Category')['Customer ID'].count()

In [18]:
df['Segment'].nunique()

3

In [19]:
df['Segment'].value_counts()

Segment
Consumer       5191
Corporate      3020
Home Office    1783
Name: count, dtype: int64

In [20]:
# good category customers
good_customer = df[df['Cust_Category']=='Great']
below_customer = df[df['Cust_Category']=='Below']
average_customer = df[df['Cust_Category']=='Average']
New_customer = df[df['Cust_Category']=='New Customer']

In [21]:
good_segment=good_customer['Segment'].value_counts()

In [22]:
below_segment=below_customer['Segment'].value_counts()

In [23]:
average_segment=average_customer['Segment'].value_counts()

In [24]:
new_segment=New_customer['Segment'].value_counts()

In [25]:
df['Country'].nunique()

1

In [26]:
df['City'].nunique()

531

In [27]:
city_freq=df['City'].value_counts()

In [28]:
def city_cat(city):
    if city > 500:
        return "Excellent"
    elif city > 300:
        return "Good"
    elif city > 100:
        return "Average"
    else:
        return "Below Average"

In [29]:
df['City_Category']=df['City'].map(city_freq).apply(city_cat)

In [30]:
df['City_Category']

0       Below Average
1       Below Average
2           Excellent
3       Below Average
4       Below Average
            ...
9989    Below Average
9990    Below Average
9991    Below Average
9992    Below Average
9993    Below Average
Name: City_Category, Length: 9994, dtype: object

In [31]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cust_Category,City_Category
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,New Customer,Below Average
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,New Customer,Below Average
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,Below,Excellent
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Below,Below Average
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Below,Below Average

In [32]:
df['City_Category'].value_counts()

City_Category
Below Average    5214
Excellent        2709
Good             1119
Average           952
Name: count, dtype: int64

In [33]:
city_excellent=df[df['City_Category'] =='Excellent']['City'].value_counts()
city_below = df[df['City_Category'] =='Below Average']['City'].value_counts()
city_good = df[df['City_Category'] =='Good']['City'].value_counts()
city_average = df[df['City_Category'] =='Average']['City'].value_counts()

In [34]:
city_excellent

City
New York City    915
Los Angeles      747
Philadelphia     537
San Francisco    510
Name: count, dtype: int64

In [35]:
city_below

City
Newark             95
Richmond           90
Jackson            82
Columbia           81
Aurora             68
                   ..
Conway              1
Normal              1
Melbourne           1
Springdale          1
San Luis Obispo     1
Name: count, Length: 518, dtype: int64

In [36]:
city_good

City
Seattle    428
Houston    377
Chicago    314
Name: count, dtype: int64

In [37]:
city_average

City
Columbus        222
San Diego       170
Springfield     163
Dallas          157
Jacksonville    125
Detroit         115
Name: count, dtype: int64

In [38]:
df['State'].nunique()

49

In [39]:
state_freq=df['State'].value_counts()

In [40]:
def state_cat(state):
    if state > 500:
        return "Maximum"
    elif state > 300:
        return "Average"
    elif state > 100:
        return "Below Average"
    else:
        return "Minimum"

In [41]:
df['State_Category'] = df['State'].map(state_freq).apply(state_cat)

In [44]:
df['State_Category']

0       Below Average
1       Below Average
2             Maximum
3             Average
4             Average
            ...
9989          Average
9990          Maximum
9991          Maximum
9992          Maximum
9993          Maximum
Name: State_Category, Length: 9994, dtype: object

In [46]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Cust_Category,City_Category,State_Category
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,New Customer,Below Average,Below Average
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,New Customer,Below Average,Below Average
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,Below,Excellent,Maximum
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,Below,Below Average,Average
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,Below,Below Average,Average

In [48]:
state_max=df[df['State_Category'] =='Maximum']['State'].value_counts()
state_belowavg = df[df['State_Category'] =='Below Average']['State'].value_counts()
state_avg = df[df['State_Category'] =='Average']['State'].value_counts()
state_min = df[df['State_Category'] =='Minimum']['State'].value_counts()

In [50]:
state_max

State
California      2001
New York        1128
Texas            985
Pennsylvania     587
Washington       506
Name: count, dtype: int64

In [52]:
state_min

State
Delaware                96
Minnesota               89
Connecticut             82
Oklahoma                66
Missouri                66
Alabama                 61
Arkansas                60
Rhode Island            56
Mississippi             53
Utah                    53
Louisiana               42
South Carolina          42
Nevada                  39
Nebraska                38
New Mexico              37
Iowa                    30
New Hampshire           27
Kansas                  24
Idaho                   21
Montana                 15
South Dakota            12
Vermont                 11
District of Columbia    10
Maine                    8
North Dakota             7
West Virginia            4
Wyoming                  1
Name: count, dtype: int64

In [55]:
state_belowavg

State
Michigan          255
North Carolina    249
Arizona           224
Virginia          224
Georgia           184
Tennessee         183
Colorado          182
Indiana           149
Kentucky          139
Massachusetts     135
New Jersey        130
Oregon            124
Wisconsin         110
Maryland          105
Name: count, dtype: int64

In [57]:
state_avg

State
Illinois    492
Ohio        469
Florida     383
Name: count, dtype: int64

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          9994 non-null   int64
 1   Order ID        9994 non-null   object
 2   Order Date      9994 non-null   object
 3   Ship Date       9994 non-null   object
 4   Ship Mode       9994 non-null   object
 5   Customer ID     9994 non-null   object
 6   Customer Name   9994 non-null   object
 7   Segment         9994 non-null   object
 8   Country         9994 non-null   object
 9   City            9994 non-null   object
 10  State           9994 non-null   object
 11  Postal Code     9994 non-null   int64
 12  Region          9994 non-null   object
 13  Product ID      9994 non-null   object
 14  Category        9994 non-null   object
 15  Sub-Category    9994 non-null   object
 16  Product Name    9994 non-null   object
 17  Sales           9994 non-null   float64
 18  Quantity        9994 non-null   int64
 19  Discount        9994 non-null   float64
 20  Profit          9994 non-null   float64
 21  Cust_Category   9994 non-null   object
 22  City_Category   9994 non-null   object
 23  State_Category  9994 non-null   object
dtypes: float64(3), int64(3), object(18)
memory usage: 1.8+ MB

In [59]:
df['Region'].nunique()

4

In [61]:
df['Region'].unique()

array(['South', 'West', 'Central', 'East'], dtype=object)

In [64]:
df['Category'].nunique()

3

In [66]:
df['Category'].value_counts()

Category
Office Supplies    6026
Furniture          2121
Technology         1847
Name: count, dtype: int64

In [67]:
df['Sub-Category'].nunique()

17

In [79]:
df[df['Category'] =='Furniture']['Sub-Category'].value_counts()

Sub-Category
Furnishings    957
Chairs         617
Tables         319
Bookcases      228
Name: count, dtype: int64

In [77]:
df[df['Category'] =='Office Supplies']['Sub-Category'].value_counts()

Sub-Category
Binders       1523
Paper         1370
Storage        846
Art            796
Appliances     466
Labels         364
Envelopes      254
Fasteners      217
Supplies       190
Name: count, dtype: int64

In [81]:
df[df['Category'] =='Technology']['Sub-Category'].value_counts()

Sub-Category
Phones         889
Accessories    775
Machines       115
Copiers         68
Name: count, dtype: int64

In [83]:
df.groupby('Cust_Category')['Sales'].mean()

Cust_Category
Average         222.471156
Below           237.350552
Great           213.574074
New Customer    220.258919
Name: Sales, dtype: float64

In [85]:
df.groupby('Cust_Category')['Profit'].mean()

Cust_Category
Average         27.973364
Below           29.731205
Great           19.875444
New Customer    29.790955
Name: Profit, dtype: float64

In [89]:
df.groupby('Cust_Category')['Discount'].mean()

Cust_Category
Average         0.161459
Below           0.152828
Great           0.143389
New Customer    0.158424
Name: Discount, dtype: float64

In [43]:
# Variables name
# customer_freq
# Cust_Category_freq
# good_customer
# below_customer
# average_customer
# New_customer
# good_segment
# below_segment
# average_segment
# new_segment
# city_freq
# city_excellent
# city_below
# city_good
# city_average
# state_freq
# state_max
# state_belowavg
# state_avg
# state_min