In [9]:
import pandas as pd

In [15]:
new_df = pd.DataFrame(columns=['name','age'])

In [16]:
new_df

Empty DataFrame
Columns: [name, age]
Index: []

In [17]:
# loc
new_df.loc[0]=['aman',23]

In [18]:
len(new_df)

1

In [19]:
new_df

   name  age
0  aman   23

In [20]:
new_df.loc[1]=['sagar',34]

In [21]:
new_df

    name  age
0   aman   23
1  sagar   34

In [22]:
new_df.loc[len(new_df)]=['john',22]

In [23]:
new_df

    name  age
0   aman   23
1  sagar   34
2   john   22

In [24]:
new_df.loc[2,"age"]=34

In [25]:
new_df

    name  age
0   aman   23
1  sagar   34
2   john   34

In [26]:
# zip method zip() combines elements position-wise."
name = ['amit','sumit','kunal']
marks = [34,54,35]

In [28]:
df_zip = pd.DataFrame(list(zip(name,marks)),columns=['name','marks'])

In [32]:
df_zip

    name  marks
0   amit     34
1  sumit     54
2  kunal     35

In [44]:
df_zip2 = zip(name,marks)

In [45]:
list1= list(df_zip2)

In [49]:
df1 = pd.DataFrame(list1,columns=['name','age'])

In [50]:
df1

    name  age
0   amit   34
1  sumit   54
2  kunal   35

In [30]:
name = ['amit','sumit','kunal']
age = [23,22,25]
subjects = ['english','science','maths','python']

In [51]:
marks=[
    [56,67,56,78],
    [34,56,78,90],
    [45,32,67,87]
]

In [54]:
df_zip3 = pd.DataFrame(
    [(name,age,*marks)
     for name,age,marks in zip (name ,age,marks)]
    ,columns=['name','age']+subjects
)

In [55]:
df_zip3

    name  age  english  science  maths  python
0   amit   23       56       67     56      78
1  sumit   22       34       56     78      90
2  kunal   25       45       32     67      87

In [57]:
name = ['amrita','sunita','kunali']
age = [23,20,26]
subjects = ['english','science','maths']
marks=[
    [56,67,56],
    [34,56,78],
    [45,32,67]
]

In [66]:
df_zip4=pd.DataFrame(
    [(name,age,*marks)
     for name,age,marks in zip(name,age,marks)]
)

In [67]:
df_zip4

        0   1   2   3   4
0  amrita  23  56  67  56
1  sunita  20  34  56  78
2  kunali  26  45  32  67

In [68]:
df_zip4.columns=['name','age']+subjects

In [69]:
df_zip4

     name  age  english  science  maths
0  amrita   23       56       67     56
1  sunita   20       34       56     78
2  kunali   26       45       32     67

In [70]:
df_calc = pd.DataFrame({
    "numbers":range(1,6),
    "squares":[x**2 for x in range(1,6)]
})

In [71]:
df_calc

   numbers  squares
0        1        1
1        2        4
2        3        9
3        4       16
4        5       25

In [72]:
df_zip4.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      str
 1   age      3 non-null      int64
 2   english  3 non-null      int64
 3   science  3 non-null      int64
 4   maths    3 non-null      int64
dtypes: int64(4), str(1)
memory usage: 252.0 bytes

In [74]:
df_zip4.describe()

        age  english    science  maths
count   3.0      3.0   3.000000    3.0
mean   23.0     45.0  51.666667   67.0
std     3.0     11.0  17.897858   11.0
min    20.0     34.0  32.000000   56.0
25%    21.5     39.5  44.000000   61.5
50%    23.0     45.0  56.000000   67.0
75%    24.5     50.5  61.500000   72.5
max    26.0     56.0  67.000000   78.0

In [75]:
df_zip4.loc[1,'name']

'sunita'

In [76]:
df_zip4.loc[1:]

     name  age  english  science  maths
1  sunita   20       34       56     78
2  kunali   26       45       32     67

In [78]:
df_zip4.loc[:,['name','age']]

     name  age
0  amrita   23
1  sunita   20
2  kunali   26

In [83]:
df_zip4[df_zip4['age']>22]

     name  age  english  science  maths
0  amrita   23       56       67     56
2  kunali   26       45       32     67

In [85]:
df_zip4[(df_zip4['age']>22) & (df_zip4['age'] <25)]

     name  age  english  science  maths
0  amrita   23       56       67     56

In [86]:
df_zip4.where((df_zip4['age']>22) & (df_zip4['age'] <25),other="not eligible")

           name           age       english       science         maths
0        amrita            23            56            67            56
1  not eligible  not eligible  not eligible  not eligible  not eligible
2  not eligible  not eligible  not eligible  not eligible  not eligible

In [90]:
df_zip4.sort_values('age',ascending=False,inplace=True)

In [91]:
df_zip4.reset_index(inplace = True)

In [92]:
df_zip4

   index    name  age  english  science  maths
0      2  kunali   26       45       32     67
1      0  amrita   23       56       67     56
2      1  sunita   20       34       56     78

In [93]:
df_zip4.drop(columns="index",inplace=True)

In [94]:
df_zip4

     name  age  english  science  maths
0  kunali   26       45       32     67
1  amrita   23       56       67     56
2  sunita   20       34       56     78